# Generated by Django 5.0.8 on 2024-08-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrada',
            name='fonte',
        ),
        migrations.AddField(
            model_name='entrada',
            name='nome',
            field=models.CharField(default=0, max_length=64, verbose_name='Nome'),
            preserve_default=False,
        ),
    ]
