# Generated by Django 5.0.7 on 2024-07-24 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_categoria_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('e', 'Entrada'), ('d', 'Despesa')], verbose_name='Tipo'),
        ),
    ]
