# Generated by Django 5.0.7 on 2024-07-12 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_metafinanceira_valor_guardar_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categoria', verbose_name='Categorias'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='data',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='nome',
            field=models.CharField(max_length=64, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor'),
        ),
    ]
