# Generated by Django 5.0.7 on 2024-07-24 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_categoria_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('Entrada', 'Entrada'), ('Despesa', 'Despesa')], verbose_name='Tipo'),
        ),
    ]
