# Generated by Django 5.0.6 on 2024-07-15 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_despesa_categoria_alter_despesa_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(max_length=64, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(max_length=64, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categoria', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='data',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='fonte',
            field=models.CharField(max_length=64, verbose_name='Fonte'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='metafinanceira',
            name='meta_valor_mes',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Meta de valor por mês'),
        ),
        migrations.AlterField(
            model_name='metafinanceira',
            name='nome',
            field=models.CharField(max_length=64, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='metafinanceira',
            name='valor_guardar_mes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Valor a guardar por mês'),
        ),
        migrations.AlterField(
            model_name='metafinanceira',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor total'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categoria', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='data',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='nome',
            field=models.CharField(max_length=64, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor'),
        ),
    ]
