# Generated by Django 5.0.7 on 2024-07-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_categoria_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='despesa',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='entrada',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='metafinanceira',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='transacao',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
